name: Continuous Integration-Continuous Deployment

on:
  push:
    branches:
      - main
jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: Docker Image Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: vmasterov/simple-react-app:latest
  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    needs: [docker_build]
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /home/vlad/simple-react-app/;docker compose stop app;docker compose rm -f app;docker rmi vmasterov/simple-react-app;docker compose up -d --force-recreate --no-deps app